name: CI

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        cc:
          - gcc
          - clang

    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: |
          sudo apt-get update -q
          sudo apt-get install -qq \
            automake autotools-dev lcov libedit-dev libeditline-dev libev-dev \
            libncurses-dev libpcre3-dev libssl-dev libtool python-docutils \
            python-sphinx

      - name: Install Varnish Cache
        run: |
          wget --no-check-certificate https://varnish-cache.org/_downloads/varnish-4.1.10.tgz
          tar zxvf varnish-*.tgz
          pushd varnish-*/
          ./autogen.sh
          CC='${{ matrix.cc }}' ./configure
          make -sj32
          sudo make PREFIX='/usr/local' install
          sudo ldconfig
          popd

      - name: Install hiredis
        run: |
          wget --no-check-certificate https://github.com/redis/hiredis/archive/v1.0.0.zip -O hiredis-1.0.0.zip
          unzip hiredis-*.zip
          pushd hiredis-*/
          make USE_SSL=1
          sudo make USE_SSL=1 PREFIX='/usr/local' install
          sudo ldconfig
          popd

      - name: Install Redis
        run: |
          wget http://download.redis.io/releases/redis-7.0.0.tar.gz
          tar zxvf redis-*.tar.gz
          pushd redis-*/
          make BUILD_TLS=yes
          sudo make BUILD_TLS=yes PREFIX='/usr/local' install
          sudo ldconfig
          popd

      - name: Build & test VMOD
        run: |
          ./autogen.sh
          CC='${{ matrix.cc }}' ./configure --prefix=/usr
          make -j4
          make check -j1
