name: CI

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        platform:
          - ubuntu-24.04
          - ubuntu-24.04-arm
        cc:
          - gcc
          - clang
        make_target:
          - check
          - distcheck
        configure_flags:
          - ''
        include:
          - platform: ubuntu-24.04
            cc: gcc
            make_target: lcov
            configure_flags: --enable-code-coverage

    steps:
      - uses: actions/checkout@v6

      - name: Build Docker image
        run: |
          docker build \
            --build-arg VARNISH_CC='${{ matrix.cc }}' \
            --tag libvmod-redis-dev \
            .

      - name: Build & test VMOD
        run: |
          docker run \
            --rm \
            --entrypoint bash \
            --volume ${{ github.workspace }}:/workspace \
            --workdir /workspace \
            libvmod-redis-dev \
            -c '\
              set -e; \
              git config --global --add safe.directory /workspace; \
              ./autogen.sh; \
              CC="${{ matrix.cc }}" ./configure --prefix=/usr ${{ matrix.configure_flags }}; \
              make -j4; \
              make ${{ matrix.make_target }} -j1'

      - name: Push code coverage
        if: ${{ matrix.make_target == 'lcov' }}
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

      - name: Show test report
        if: ${{ failure() }}
        run: |
          cat src/test-suite.log || exit 0
