name: CI

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        platform:
          - ubuntu-24.04
          - ubuntu-24.04-arm
        cc:
          - gcc
          - clang
        make_target:
          - check
          - distcheck
        configure_flags:
          - ''
        protocol:
          - default
          - RESP2
          - RESP3
        tls:
          - 'false'
          - 'true'
        exclude:
          # Only exercise protocol & TLS combinations with 'make check':
          # 'make distcheck' already runs the test suite once internally
          # using the defaults.
          - make_target: distcheck
            protocol: RESP2
          - make_target: distcheck
            protocol: RESP3
          - make_target: distcheck
            tls: 'true'
        include:
          - platform: ubuntu-24.04
            cc: gcc
            make_target: lcov
            configure_flags: --enable-code-coverage
            protocol: default
            tls: 'false'

    steps:
      - uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      # docker build \
      #   --build-arg VARNISH_CC='${{ matrix.cc }}' \
      #   --tag libvmod-redis-dev \
      #   .
      - name: Build Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          load: true
          tags: libvmod-redis-dev
          build-args: VARNISH_CC=${{ matrix.cc }}
          cache-from: type=gha,scope=${{ matrix.platform }}-${{ matrix.cc }}
          cache-to: type=gha,mode=max,scope=${{ matrix.platform }}-${{ matrix.cc }}

      - name: Build & test VMOD
        run: |
          docker run \
            --rm \
            --entrypoint bash \
            --volume ${{ github.workspace }}:/workspace \
            --workdir /workspace \
            libvmod-redis-dev \
            -c '\
              set -e; \
              git config --global --add safe.directory /workspace; \
              ./autogen.sh; \
              CC="${{ matrix.cc }}" ./configure --prefix=/usr ${{ matrix.configure_flags }}; \
              make -j4; \
              PROTOCOL="${{ matrix.protocol }}" TLS="${{ matrix.tls }}" make ${{ matrix.make_target }} -j1'

      - name: Push code coverage
        if: ${{ matrix.make_target == 'lcov' }}
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

      - name: Show test report
        if: ${{ failure() }}
        run: |
          cat src/test-suite.log || exit 0
